[files]
extend-exclude = ["pt-BR", "de", "ja", "es", "blog/202[0-3]*", "commands/", "fr"]

[default.extend-words]
ons = "ons" # false positive in commands/docs/str_replace.md
ful = "ful" # false positive in commands/docs/str_replace.md
optio = "optio" # false positive in cookbook/http.md
"ime" = "ime" # false positive in cookbook/polars_v_pandas_v_nushell.md
ws = "ws" # false positive in book/nushell_map.md
ratatui = "ratatui"
doas = "doas"
iterm = "iterm"
nushell = "nushell"
ba = "ba"
guid = "guid"
